const POT = 35;


//letreiro
Graphics.prototype.setFontNotoSansJP = function () {
    // Actual height 8 (7 - 0)
    // 1 BPP
    return this.setFontCustom(
        atob('AAB6egBg4OBgAD5+fn4AMvvfTgB4en48fl4eAC5+fnYOAGDgAHz/gwDH/zgAYODgQAAYPDwYAAcGAAgICAACAgAPfvAAPn5mfgACfn4CAGJGfnoAYlp+fgAcPH5+AHJyWl4APn5aXgBATn5wAH5+en4AenpufgASEgAnJgAYGDw0ADw8PDwAJDwYGABAXnpwADx+/7+//nw4AA5+fH4OAH5+Wn5+ADx+QkJCAH5+QmZ+GAB+flpaQgB+flhYADx+Sk5ODgB+fhgYfn4Afn4AAgJ+fgB+fjh+RgB+fgICAH5+fB5+fgB+fjgefn4APH5CQn48AH5+SHhwAHj8hof/ewB+fkx+dgByclpOTgBAfn5+QAB8fgIGfnwAeH4efnAAfH5+eH5+fABmfjx+QgBwfj5wAEZOfnJiAP//AQDg/B8AAf/+ABh4cDgAAwMDAwAAwMAAFj4+Pg4A/v4yPh4AHj4yMgAePjL+/gAePjo6AH7+8AA/f31/QwD+/jA+HgB+fgD//wD+/hw+AP7+AD4+MD4+Pj4APj4wPh4AHj4yPh4Af39kfDwAPHxkf38APj4wABo6PhYAfn4yAD4+Aj4+ADweHjwAPB4+Ph4+ADYeHjYAcT8/eAA2Pj4yAP7/AQD+/gDv/xAAGBgYGAA='),
        32,
        atob("AgMFBQUIBgMEBAUFAwQDBAUFBQUFBQUFBQUDAwUFBQUJBgYGBwYFBwcDBQYFBwcHBgcGBgYHBggGBQYEBAQFBQQGBgUGBQQGBgMDBQMIBgYGBgQFBAYFBwUFBQQDBAU="),
        8 | 65536
    );
}

// 128x64
const velocimetro = atob("gEABAAAAAAAAH/+AAAAAAAAAAAAAAAAAAf//+AAAAAAAAAAAAAAAAAf///4AAAAAAAAAAAAAAAAf4AB/gAAAAAAAAAAAAAAAfg//B+AAAAAAAAAAAAAAAfh//+H4AAAAAAAAAAAAAAPj///8fAAAAAAAAAAAAAAHz/Bg/z4AAAAAAAAAAAAADx+AYB+PAAAAAAAAAAAAAB5+AGAH54AAAAAAAAAAAAA8/gBgB/PAAAAAAAAAAAAAeecAYA554AAAAAAAAAAAAPPGAGAGPPAAAAAAAAAAAAHngAAAAB5wAAAAAAAAAAABzwAAAAAPOAAAAAAAAAAAA94AAAAAB5wAAAAAAAAAAAOcAAAAAAOcAAAAAAAAAAAHOAAAAAABzgAAAAAAAAAAB3gAAAAAAe4AAAAAAAAAAA5+AAAAAAfnAAAAAAAAAAAO/gAAAAAH9wAAAAAAAAAAHOQAAAAAAnOAAAAAAAAAABzgAAAAAABzgAAAAAAAAAAdwAAAAAAAO4AAAAAAAAAAHcAAAAAAADuAAAAAAAAAADnAAAAAAAA5wAAAAAAAAAA7gAAAAAAAHcAAAAAAAAAAO4AAAGAAAB3AAAAAAAAAADuAAAH4AAAdwAAAAAAAAAA7gAAD/AAAHcAAAAAAAAAAO4AAA/wAAB3AAAAAAAAAADv+AAf+AAf9wAAAAAAAAAA7/gAH/gAH/cAAAAAAAAAAO4AAA/wAAB3AAAAAAAAAADuAAAP8AAAdwAAAAAAAAAA7gAAB+AAAHcAAAAAAAAAAO4AAAGAAAB3AAAAAAAAAADuAAAAAAAAdwAAAAAAAAAA5wAAAAAAAOcAAAAAAAAAAHcAAAAAAADuAAAAAAAAAAB3AAAAAAAA7gAAAAAAAAAAc4AAAAAAAc4AAAAAAAAAAHOAAAAAAAHOAAAAAAAAAAA7+AAAAAAf3AAAAAAAAAAAOfgD///AH5wAAAAAAAAADh3gD///8Ae4cccAAAAAABEc4A////AHOIoogAAAAAARDnAO7ndwDnAKKIAAAAAAEQ54Du53cB7wCiiAAAAAABEHPA7ud3A84BIogAAAAAARA54P///wecAiKIAAAAAAEQPPD///8PPAQiiAAAAAAA4B54P//8HngPnHAAAAAAAAAPPgAAAHzwAAAAAAAAAAAAB5+AAAH54AAAAAAAAAAAAAPH4AAH48AAAAAAAAAAAAAB8/wAP8+AAAAAAAAAAAAAAPj///8fAAAAAAAAAAAAAAA+H//4fAAAAAAAAAAAAAAAH4P/wfgAAAAAAAAAAAAAAAf4AB/gAAAAAAAAAAAAAAAB////gAAAAAAAAAAAAAAAAH///gAAAAAAAAAAAAAAAAAH/+AAAAAAAAAAA==");

I2C1.setup();
let oled = require('SSD1306').connect(I2C1);

setInterval(() => {
    let valorPot = analogRead(POT);
    let ang = 240 * valorPot - 210;
    let rad = ang * Math.PI / 180;
    let veloc = 200 * valorPot;
    let x = 20 * Math.cos(rad) + 58;
    let y = 20 * Math.sin(rad) + 32;
    oled.clear();
    oled.drawImage(velocimetro, 0, 0)
    oled.drawLine(58, 32, x, y)
    oled.setFontNotoSansJP();
    oled.drawString('V:', 0, 0)
    oled.drawString(veloc.toFixed(0), 0, 12);
    oled.flip();
}, 100)